version: "3"
services:
    postgres:
        image: postgres
        container_name: "db"
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=db
        ports:
            - "5455:5432"
        volumes:
            - "./db:/var/lib/postgresql/data/"